name: isar_test

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  intl:
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
  json_annotation: ^4.9.0
  meta: ^1.16.0
  path:
  path_provider:
  test: any

dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0

dependency_overrides:
  dart_style:
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
