name: isar
description: Extremely fast, easy to use, and fully async NoSQL database for Flutter.
version: 0.0.0-placeholder
repository: https://github.com/isar/isar/tree/main/packages/isar
homepage: https://github.com/isar/isar
issue_tracker: https://github.com/isar/isar/issues
documentation: https://isar.dev
funding:
  - https://github.com/sponsors/simc/
topics:
  - database
  - isar
  - sqlite
  - encryption
  - storage

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  analyzer:
  build:
  ffi:
  meta:
  source_gen:
  web:

dev_dependencies:
  build_test:
  ffigen:
  test:
  very_good_analysis:
